---
hier_options:
  #Enabled/Disables idempotent ACL handling for IOS-XR
  idempotent_acl_iosxr: true

  #if there is a delta, overwrite these parents instead of one of their children
  sectional_overwrite:
  - ^template

  sectional_overwrite_no_negate:
  - ^as-path-set
  - ^prefix-set
  - ^route-policy
  - ^extcommunity-set
  - ^community-set

  parent_allows_duplicate_child:
  - ^route-policy

  sectional_exiting:
  - parent_expression: ^route-policy
    exit_text: end-policy
  - parent_expression: ^policy-map
    exit_text: end-policy-map

  #adds +1 indent to lines following start_expression and removes the +1 indent for lines following end_expression
  indent_adjust:
  - start_expression: ^\s*template
    end_expression: ^\s*end-template

  #substitions against the full multi-line config text
  full_text_sub:
  - search: 'banner exec (\^?\S)\w*\n(.*\n)+\\1\s*\n'
    replace: ''
  - search: 'banner motd (\^?\S)\w*\n(.*\n)+\\1\s*\n'
    replace: ''

  #substitions against each line of the config text
  per_line_sub:
  - search: ^Building configuration.*
    replace: ''
  - search: .*message-digest-key.*
    replace: ''
  - search: .*password.*
    replace: ''

  idempotent_commands_blacklist: []

  #These commands do not require negation, they simply overwrite themselves
  idempotent_commands:
  - ^\s*cost
  - logging \d+.\d+.\d+.\d+ vrf MGMT
  - soft-reconfiguration inbound

  #Default when expression: list of expressions
  negation_default_when: []
  #- expressions

  #Negate substitutions: expression -> negate with
  negation_negate_with: []
  #- match: expression
  #  use: command
